### ISSUE TITLE
Fit Game_Object creation to window

### ISSUE THREAD

**Issue by dennisn00** [Aehrlich98/geocrash#4]
When Game_Objects (incl. the Player) are created, their position should be within the windows bounds. The context object is borrowed to provide the position information.

Questions:
Should the player be created in the center of the window or at a random position?

**Comment by Aehrlicher** [comment]
If we have two players opposing each other, each could be placed in the center of their half of the level. 
In  case of a single player, the center should be alright.

**Comment by Aehrlicher** [comment]
Solved (temporarily ?) by using ggez::conf::WindowMode struct to hold custom window settings in main and passing it on to master as well as passing the bounds to game_object::new() to let them have access to the settigns.
